apiVersion: v1
kind: Service
metadata:
  name: numbersnme-service
spec:
  selector:
    app: numbersnme
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # Or LoadBalancer if external access needed
